---
- name: See if ecs-agent is stopped
  shell: "docker ps -a -f name='ecs-agent' -f status=running"
  register: ecs_agent_running
  changed_when: false #Since this is just info gathering, no need to report the change
  ignore_errors: yes
- name: Remove any old ecs-agents
  shell: "docker rm -f ecs-agent"
  ignore_errors: yes
  when: ecs_agent_running.stdout.find('amazon/amazon-ecs-agent') < 1
- name: Start ecs-agent
  shell: docker run --name ecs-agent \
        --detach=true \
        --restart=on-failure:10 \
        --volume={{docker_socket}}:/var/run/docker.sock \
        --volume=/var/log/ecs/:/log \
        --volume=/var/lib/ecs/data:/data \
        --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro \
        --volume=/var/run/docker/execdriver/native:/var/lib/docker/execdriver/native:ro \
        --publish=127.0.0.1:51678:51678 \
        --env=ECS_LOGFILE=/log/ecs-agent.log \
        --env=ECS_LOGLEVEL=info \
        --env=ECS_DATADIR=/data \
        --env=ECS_CLUSTER={{ecs_cluster_name}} \
        {{ecs_agent_container}}
  when: ecs_agent_running.stdout.find('amazon/amazon-ecs-agent') < 1
